import math
import xml.etree.ElementTree as ET

import numpy as np

from inference.API.rmvpe_api import RmvpeResult
from inference.API.vsqx_api import save_vsqx
from inference.io.note_io import NoteInfo


def test_vsqx_export_writes_notes_and_skips_invalid(tmp_path):
    path = tmp_path / "notes.vsqx"
    save_vsqx([NoteInfo(0, 0.5, 60, "la"), NoteInfo(0.6, 0.4, 60, "bad"), NoteInfo(1, 2, math.nan, "bad")], path)
    root = ET.parse(path).getroot()
    ns = {"v": "http://www.yamaha.co.jp/vocaloid/schema/vsq4/"}
    notes = root.findall(".//v:note", ns)
    assert len(notes) == 1
    assert notes[0].findtext("v:n", namespaces=ns) == "60"
    assert notes[0].findtext("v:y", namespaces=ns) == "la"
    assert root.find("v:masterTrack", ns) is not None
    assert root.findtext("v:masterTrack/v:comment", namespaces=ns) == "Generated by Vocal2Midi"
    part = root.find(".//v:vsPart", ns)
    assert part.findtext("v:name", namespaces=ns) == "notes"


def test_vsqx_export_writes_vocaloid_pitch_controls(tmp_path):
    path = tmp_path / "pitch.vsqx"
    result = RmvpeResult(
        time_step_seconds=0.01,
        midi_pitch=np.full(100, 60.5, dtype=np.float32),
        voiced_mask=np.ones(100, dtype=bool),
    )
    save_vsqx([NoteInfo(0, 1, 60.4, "la")], path, tempo=120, rmvpe_result=result)

    root = ET.parse(path).getroot()
    ns = {"v": "http://www.yamaha.co.jp/vocaloid/schema/vsq4/"}
    controls = root.findall(".//v:vsPart/v:cc", ns)
    pit = [c for c in controls if c.find("v:v", ns).get("id") == "P"]
    assert pit
    assert int(pit[0].findtext("v:v", namespaces=ns)) == 0
    assert pit[0].findtext("v:t", namespaces=ns) == "0"
    assert int(pit[1].findtext("v:v", namespaces=ns)) == 0
    assert int(pit[-1].findtext("v:v", namespaces=ns)) == 0
    assert pit[-1].findtext("v:t", namespaces=ns) == "960"

    ids = [c.find("v:v", ns).get("id") for c in controls]
    assert ids == sorted(ids, reverse=True)
    part = root.find(".//v:vsPart", ns)
    assert part.findtext("v:playTime", namespaces=ns) == "960"


def test_vsqx_pitch_ignores_unvoiced_interpolated_frames(tmp_path):
    path = tmp_path / "unvoiced.vsqx"
    voiced_mask = np.ones(100, dtype=bool)
    voiced_mask[25:75] = False
    result = RmvpeResult(
        time_step_seconds=0.01,
        midi_pitch=np.full(100, 60.5, dtype=np.float32),
        voiced_mask=voiced_mask,
    )
    save_vsqx([NoteInfo(0, 1, 60, "la")], path, tempo=120, rmvpe_result=result)

    root = ET.parse(path).getroot()
    ns = {"v": "http://www.yamaha.co.jp/vocaloid/schema/vsq4/"}
    pit_ticks = []
    for control in root.findall(".//v:vsPart/v:cc", ns):
        value = control.find("v:v", ns)
        if value.get("id") == "P" and int(value.text) != 0:
            pit_ticks.append(int(control.findtext("v:t", namespaces=ns)))

    assert pit_ticks
    assert not any(240 <= tick < 720 for tick in pit_ticks)


def test_vsqx_pitch_writes_dynamic_bend_sensitivity_before_pit(tmp_path):
    path = tmp_path / "pbs.vsqx"
    result = RmvpeResult(
        time_step_seconds=0.01,
        midi_pitch=np.full(100, 63.0, dtype=np.float32),
        voiced_mask=np.ones(100, dtype=bool),
    )
    save_vsqx([NoteInfo(0, 1, 60, "la")], path, tempo=120, rmvpe_result=result)

    root = ET.parse(path).getroot()
    ns = {"v": "http://www.yamaha.co.jp/vocaloid/schema/vsq4/"}
    controls = root.findall(".//v:vsPart/v:cc", ns)
    ids = [control.find("v:v", ns).get("id") for control in controls]
    first_pit = ids.index("P")

    assert ids[:first_pit] == ["S", "S"]
    assert all(control_id == "P" for control_id in ids[first_pit:])
    assert controls[0].findtext("v:t", namespaces=ns) == "0"
    assert controls[0].findtext("v:v", namespaces=ns) == "3"
    assert controls[1].findtext("v:v", namespaces=ns) == "2"
    assert any(
        control.find("v:v", ns).get("id") == "P" and control.findtext("v:v", namespaces=ns) == "8191"
        for control in controls
    )
